name: Windows

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  msvc2019:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]
    
    steps:
    - uses: actions/checkout@v3
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
        boost_version: 1.78.0
        boost_install_dir: C:\boost_1_78_0
        platform_version: 2019
        toolset: msvc
    - name: CMake configure
      run: |
        cmake -S . -B build -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} -D BUILD_TEST=ON -D BUILD_EXAMPLE=ON
    - name: CMake build
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel 10
    - name: CTest
      run: |
        cd build
        ctest -j 10 -C ${{ matrix.build_type }} --output-on-failure