name: Windows

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  BOOST_ROOT: C:\boost_1_78_0
  BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.bz2/download

jobs:
  MSVC:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]
        generator_type: [Visual Studio 15 2017, Visual Studio 16 2019, Visual Studio 17 2022]
    
    steps:
    - uses: actions/checkout@v3

    # source: https://github.com/actions/runner-images/issues/2667#issuecomment-778655341 
    - name: Restore Boost cache
      uses: actions/cache@v3
      id: cache-boost
      with:
        path: ${{ env.BOOST_ROOT }}
        key: boost_1_78_0

    - name: Download Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        if [ "$OS" == "Windows_NT" ]; then
          # fix up paths to be forward slashes consistently
          BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        fi
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && cp -r boost_*/* .
        rm -rf boost_*/* download.tar.bz2 download.tar
      shell: bash

    - name: CMake configure
      run: |
        cmake -S . -B build -G "${{ matrix.generator_type }}" -A ${{ matrix.architecture }} -D BUILD_TEST=ON -D BUILD_EXAMPLE=ON
      env:
        BOOST_ROOT: ${{ env.BOOST_ROOT }}

    - name: CMake build
      run: |
        cmake --build build --config ${{ matrix.build_type }}

    - name: Run test
      run: |
        cd build/test/${{ matrix.build_type }}
        shared_memory_test.exe